### PR TITLE
docs: development with tilt

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

Added initial documentation on development/debugging locally using tilt. This is the start of the developer documentation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits into logical changes
- [x] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Callisto13** [comment]
@richardcase can you add something on how to use failure domains? I put something in at the mvm level to get people going for now, but would be good to know how to do this from the cluster level

**Comment by richardcase** [comment]
> @richardcase can you add something on how to use failure domains? I put something in at the mvm level to get people going for now, but would be good to know how to do this from the cluster level

Yes i will add that now :+1:

**Comment by richardcase** [comment]
Currently blocked on #59 .....on investigation the way we where handling failure domains at the cluster level was wrong.

**Comment by richardcase** [comment]
Updated the docs based on #59

**Review by Callisto13 — APPROVED** [review]

**Pull request merged**
