### PR TITLE
fix: issues with tokens in the templates

### PR DESCRIPTION
**Pull request by richardcase**
**What this PR does / why we need it**:

Fixed a couple of issues with tokens in the cluster templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

### CODE REVIEW

**Comment by Callisto13** [comment]
how would we add ssh keys?

**Comment by richardcase** [comment]
> how would we add ssh keys?

I think a bit like the other settings, if you want to set SSH keys then you have to generate and edit the manifests.

**Comment by Callisto13** [comment]
ah okay

**Review by Callisto13 — APPROVED** [review]
Alt Text

**Pull request merged**
